name: pangu_grpo_backup_do_not_use
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - ca-certificates=2025.9.9=hd43f75c_0
  - ld_impl_linux-aarch64=2.40=h48e3ba3_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - tzdata=2025b=h04d1e81_0
  - libgomp=11.2.0=h1234567_1
  - _openmp_mutex=5.1=51_gnu
  - libgcc-ng=11.2.0=h1234567_1
  - bzip2=1.0.8=h998d150_6
  - libffi=3.4.4=h419075a_1
  - libuuid=1.41.5=h998d150_0
  - libzlib=1.3.1=h998d150_0
  - ncurses=6.5=h419075a_0
  - openssl=1.1.1w=h2f4d8fa_0
  - pthread-stubs=0.3=hfd63f10_1
  - xorg-libxau=1.0.12=hf66535e_0
  - xorg-libxdmcp=1.1.5=hf66535e_0
  - xorg-xorgproto=2024.1=h998d150_1
  - xz=5.6.4=h998d150_1
  - libxcb=1.17.0=hf66535e_0
  - readline=8.3=h886d1d0_0
  - zlib=1.3.1=h998d150_0
  - sqlite=3.50.2=h998d150_1
  - xorg-libx11=1.8.12=hf66535e_1
  - tk=8.6.15=h987d8db_0
  - python=3.11.0=h89984f6_3
  - setuptools=78.1.1=py311hd43f75c_0
  - wheel=0.45.1=py311hd43f75c_0
  - pip=25.2=pyhc872135_0
prefix: /root/miniconda3/envs/pangu_grpo_backup_do_not_use
